### ISSUE TITLE
Code do not work (anymore?)

### ISSUE THREAD

**Issue by stevexyz** [MarquisdeGeek/LichessBots#1]
Code seems not anymore valid. Tried to run a bot (the random one) and got error. Below error is not the first try (on it the bot made a single move and got same error).

```Starting stream at stream/event
STREAM data : "gameStart"
STREAM data : "gameStart"
INFO Playing: 2  Waiting for humans: 2
INFO Playing: 2  Waiting for humans: 2
INFO Playing: 2  Waiting for humans: 2
ENGINE getGameList failed FetchError: invalid json response body at https://lichess.org/api/account/playing reason: Unexpected token < in JSON at position 0
(node:127787) UnhandledPromiseRejectionWarning: Error: Could not retrieve games list
    at /LichessBots/src/lib/server.js:148:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:127787) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:127787) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
STREAM data : "challenge"
STREAM data : "gameStart"
```

**Comment by MarquisdeGeek** [comment]
I get this occasionally too, usually because the lichess site gets confused on the requests and rate limits. (I've gotten "ETIMEDOUT" a lot recently.) Changing the setTimeouts() in pollServer() in lib/server.js might help this.

Happy for patches to correctly handle the 429 responses.
